"""empty message

Revision ID: 139c95be9241
Revises: 
Create Date: 2022-01-29 16:52:28.279256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "139c95be9241"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("contact_no", sa.String(length=15), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("email_id", sa.String(length=500), nullable=True),
        sa.Column("interests", sa.String(length=500), nullable=True),
        sa.Column("profile_photo", sa.String(length=500), nullable=True),
        sa.Column("places_visited", sa.String(length=500), nullable=True),
        sa.Column("other_info", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "trips",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("hosted_by", sa.BigInteger(), nullable=False),
        sa.Column("destination", sa.String(length=500), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("events", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("additional_info", sa.String(length=500), nullable=True),
        sa.Column("date_from", sa.DateTime(), nullable=True),
        sa.Column("date_to", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["hosted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("trips")
    # ### end Alembic commands ###
